# Generated by Django 5.0.6 on 2024-06-11 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('white_wins', models.IntegerField(default=0)),
                ('black_wins', models.IntegerField(default=0)),
                ('draws', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('white_time', models.FloatField(verbose_name=180.0)),
                ('black_time', models.FloatField(verbose_name=180.0)),
                ('move_list', models.TextField()),
                ('finished', models.BooleanField(default=False)),
                ('winner', models.IntegerField()),
                ('game_set', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='witch_chess_app.gameset')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='gameset',
            name='black',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_black', to='witch_chess_app.profile'),
        ),
        migrations.AddField(
            model_name='gameset',
            name='white',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_white', to='witch_chess_app.profile'),
        ),
    ]
