# Generated by Django 5.0.6 on 2024-06-12 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('witch_chess_app', '0003_gameset_lobby_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameset',
            name='black',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_black', to='witch_chess_app.client'),
        ),
        migrations.AlterField(
            model_name='gameset',
            name='white',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_white', to='witch_chess_app.client'),
        ),
    ]
