# Generated by Django 5.0.6 on 2024-06-12 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('witch_chess_app', '0006_lobby_black_lobby_white_alter_gameset_black_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameset',
            name='black',
        ),
        migrations.RemoveField(
            model_name='gameset',
            name='lobby_code',
        ),
        migrations.RemoveField(
            model_name='gameset',
            name='white',
        ),
    ]
