# Generated by Django 5.0.6 on 2024-06-14 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('witch_chess_app', '0007_remove_gameset_black_remove_gameset_lobby_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='black_turns',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='start_time',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='white_turns',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='black_time',
            field=models.FloatField(default=180.0),
        ),
        migrations.AlterField(
            model_name='game',
            name='white_time',
            field=models.FloatField(default=180.0),
        ),
        migrations.AlterField(
            model_name='game',
            name='winner',
            field=models.IntegerField(default=0),
        ),
    ]
