# Generated by Django 5.0.6 on 2024-06-19 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('witch_chess_app', '0008_game_black_turns_game_start_time_game_white_turns_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobby',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
