# Generated by Django 5.0.6 on 2024-06-21 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('witch_chess_app', '0009_lobby_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameset',
            name='last_state',
            field=models.TextField(default='null'),
        ),
        migrations.AddField(
            model_name='gameset',
            name='last_turn',
            field=models.TextField(default='White'),
        ),
    ]
