# Generated by Django 5.0.6 on 2024-06-21 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('witch_chess_app', '0010_gameset_last_state_gameset_last_turn'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='wins',
            field=models.IntegerField(default=0),
        ),
    ]
